.github/workflows/build.yaml, .github/workflows/tests.yaml
I'm not completely sure whether I can reuse the artifact on a production environment. The first step is to separate a build from a test.
Once this Workflow passes, I am going to refactor the tests workflow to pull the artifact stored by this workflow.
=> feat: add Build Workflow

resources/views/welcome.blade.php
This is to test our deployment with Uberspace.
=> feat: swap footer

package-lock.json, package.json, resources/js/app.js, resources/sass/app.scss, resources/views/layouts/app.blade.php, resources/views/layouts/guest.blade.php, vite.config.js
Tell the world … um … Laravel and Vite about it!
=> feat: install Bootstrap

resources/views/auth/register.blade.php
=> fix: associate label with right checkbox

lang/de/messages.php, lang/en/messages.php, resources/views/auth/login.blade.php, tests/Browser/LoginTest.php
Except social login this is now fully implemented. We have even tests to ensure it's working!
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> refactor: adjust login template to our needs

.github/workflows/build.yaml, .github/workflows/tests.yaml
Let's see whether GitHub Actions can pull this off. (Requires a desktop setup usually.)
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> test: add a test to execute browser tests on CI

lang/de/messages.php, lang/en/messages.php, package-lock.json, package.json, resources/js/bootstrap.js, resources/sass/app.scss, resources/views/dashboard.blade.php
This is displaying a range of important navigation items as icon bar.
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> feat: adjust navbar to our needs

composer.lock
Dependabot's PR failed, so here we go again.
Replaces #57
=> chore: bump PHP dependencies

lang/de/messages.php, lang/en/messages.php, resources/views/components/footer.blade.php
This covers links to documents Jetstream is providing to us already.
Touches on #32.
=> feat: add footer

resources/views/auth/register.blade.php
Still not tracked in the database.
=> fix: markup newsletter as optional

resources/views/welcome.blade.php
Pushed the footer to the bottom. Might need more layout.
=> feat: use the footer component

app/Http/Controllers/EventController.php, app/Http/Requests/StoreEventRequest.php, app/Models/Event.php, lang/de/messages.php, lang/en/messages.php, resources/views/components/event/card.blade.php, resources/views/components/textarea.blade.php, resources/views/event-create.blade.php, resources/views/welcome.blade.php
I can haz Events!
No relations, but still. I count this as success!
=> feat: create events

app/Http/Controllers/EventController.php
I'm new to Laravel and learned a better way of writing this!
Extracted from #86
Co-authored-by: Stephano Vogel <stephano.vogel@outlook.com>
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> refactor: idiomatic use of Controller

app/Http/Requests/StoreEventRequest.php, resources/views/events/create.blade.php
At least for the inputs we already have.
Based on #86
=> feat: add event validation

.github/workflows/tests.yaml
=> Fix test workflows

.github/workflows/tests.yaml, composer.lock, tests/Browser/LoginTest.php
Now the logout is not hidden behind a dropdown anymore. The tests require an update.
I'm surprised that my last PR on this did not fail.
=> test: fix logout

resources/views/dashboard.blade.php
@Ryuno-Ki kannst du es bitte überprüfen?
=> route show profile

app/Http/Controllers/EventController.php, app/Models/Event.php, app/Models/Organizer.php, app/Models/User.php, database/seeders/OrganizerSeeder.php, resources/views/welcome.blade.php
Otherwise we cannot set the organizer_id on Events!
=> feat: hide create event from anon users

resources/views/components/authentication-card.blade.php
Better adjust the columns spanned.
=> fix: layout auth forms responsively

resources/markdown/Impressum.md, resources/markdown/policy.md, resources/markdown/terms.md
Impressum, Datenschutz und AGB wurden entsprechen der DDG angepasst. Fomrmatierung für bessere Lesbarkeit wurde ebenfalls durchgeführt.
=> Anpassungen

tests/Browser/LoginTest.php, tests/Browser/RegisterTest.php, tests/Feature/AuthenticationTest.php, tests/Feature/EmailVerificationTest.php, tests/Feature/RegistrationTest.php
Adjusted test to match changes in default route after login and page layout
=> Browser & Feature Test fixes

resources/views/dashboard.blade.php
=> menue-theming

app/Http/Controllers/EventController.php, app/Http/Requests/StoreEventRequest.php, app/Livewire/SearchableDropdown.php, app/Models/Area.php, app/Models/Event.php, app/Models/EventPlace.php, lang/de/messages.php, resources/views/components/event/card.blade.php, resources/views/components/searchable-dropdown.blade.php, resources/views/components/textarea.blade.php, resources/views/events/create.blade.php
... and respect the chosen place in the event card
=> Add Event Places to the Event creation page

.github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/tests.yaml, deploy.yaml
- Removed old cachetool artifacts form Deployer config file
=> feat: add PHP 8.4 to the deployment matrix
